# Generated by Django 5.0.4 on 2024-04-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='liked_cars',
            field=models.ManyToManyField(blank=True, to='vehicles.vehicle'),
        ),
    ]
