# Generated by Django 5.0.4 on 2024-04-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_appuser_liked_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='avarage_rating',
            field=models.FloatField(blank=True, default=3, null=True),
        ),
    ]
