# Generated by Django 5.0.4 on 2024-04-18 14:16

import VehicleRental.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appuser_avarage_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, validators=[VehicleRental.core.validators.validate_all_capital])),
                ('price_to_bgn', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
