# Generated by Django 5.0.4 on 2024-04-09 20:38

import VehicleRental.vehicles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.IntegerField(validators=[VehicleRental.vehicles.validators.validate_year_from_1900_to_current])),
                ('photo', models.ImageField(blank=True, upload_to='car_photos', validators=[VehicleRental.vehicles.validators.validate_image_less_than_5mb])),
            ],
        ),
    ]
