# Generated by Django 5.0.4 on 2024-04-13 21:05

import VehicleRental.core.validators
import VehicleRental.vehicles.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(40), VehicleRental.core.validators.validate_only_letters])),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.IntegerField(validators=[VehicleRental.vehicles.validators.validate_year_from_1900_to_current])),
                ('photo', models.ImageField(blank=True, upload_to='car_photos', validators=[VehicleRental.vehicles.validators.validate_image_less_than_5mb])),
                ('price_per_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vehicles.location')),
            ],
        ),
    ]
