# Generated by Django 5.0.4 on 2024-04-20 09:27

import VehicleRental.vehicles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_price_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(upload_to='car_photos', validators=[VehicleRental.vehicles.validators.validate_image_less_than_5mb]),
        ),
    ]
