# Generated by Django 5.0.4 on 2024-04-11 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_location_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='common.location'),
            preserve_default=False,
        ),
    ]
