# Generated by Django 5.0.4 on 2024-04-11 18:49

import VehicleRental.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_listing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price_per_day',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2), VehicleRental.core.validators.validate_only_letters]),
        ),
    ]
